steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/psychic-raceway-461010-a1/my-docker-repo/etl-microservice', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/psychic-raceway-461010-a1/my-docker-repo/etl-microservice']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', 'etl-microservice',
    '--image', 'us-central1-docker.pkg.dev/psychic-raceway-461010-a1/my-docker-repo/etl-microservice',
    '--region', 'us-central1',
    '--platform', 'managed',
  ]


options:
  logging: CLOUD_LOGGING_ONLY